[package]
name = "nomad-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Substrate
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.0", default-features = false, features = ["derive"] }
sp-std = { version = "4.0.0-dev", default-features = false }
sp-core = { version = "6.0.0", default-features = false }
sp-io = { version = "6.0.0", default-features = false }
sp-runtime = { version = "6.0.0", default-features = false }
frame-support = { version = "4.0.0-dev", default-features = false }
parity-util-mem = { version = "0.11.0", default-features = false, features = ["primitive-types"] }

primitive-types = { version = "0.12.0", default-features = false, features = ["scale-info", "codec"] }
tiny-keccak = { version = "2.0.2", default-features = false, features = ["keccak"] }
signature = { path = "../signature", default-features = false }
getrandom = { version = "0.2", default-features = false, features = ["js"] }

serde = { version = "1.0", default-features = false, optional = true, features = ["derive"] }
ethers-core = { version = "0.13.0", optional = true }
ethers-signers = { version = "0.13.0", optional = true }

[dev-dependencies]
async-trait = "0.1.42"

[features]
default = ["std"]
std = [
	"serde",
	"ethers-core",
	"ethers-signers",
	"primitive-types/serde",
	"signature/std",
	"codec/std",
	"scale-info/std",
	"frame-support/std",
]

