[package]
name = "nomad-base"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
frame-support = { version = "4.0.0-dev", default-features = false }
nomad-core = { path = "../nomad-core", default-features = false }
parity-util-mem = { version = "0.10.2", default-features = false, features = ["primitive-types"] }
primitive-types = { version = "0.10.1", default-features = false, features = ["scale-info", "codec"] }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }
serde = { version = "1.0", default-features = false, optional = true, features = ["derive"] }
signature = { path = "../signature", default-features = false }
sp-core = { version = "4.0.0-dev", default-features = false }
sp-io = { version = "4.0.0-dev", default-features = false }
sp-std = { version = "4.0.0-dev", default-features = false }
tiny-keccak = { version = "2.0.2", default-features = false, features = ["keccak"] }

[dev-dependencies]
ethers-signers = "0.13.0"
once_cell = "1.8.0"

[features]
default = ["std"]
std = [
	"serde",
	"primitive-types/serde",
	"codec/std",
	"scale-info/std",
	"frame-support/std",
	"nomad-core/std",
]
