[package]
name = "nomad-base"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Substrate
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }
sp-std = { version = "4.0.0-dev", default-features = false }
sp-core = { version = "4.0.0-dev", default-features = false }
sp-io = { version = "4.0.0-dev", default-features = false }
frame-support = { version = "4.0.0-dev", default-features = false }
parity-util-mem = { version = "0.10.2", default-features = false, features = ["primitive-types"] }

primitive-types = { version = "0.10.1", default-features = false, features = ["scale-info", "codec"] }
tiny-keccak = { version = "2.0.2", default-features = false, features = ["keccak"] }
signature = { path = "../signature", default-features = false }

nomad-core = { path = "../nomad-core", default-features = false }

[dependencies.ethers-signers]
version = "0.13.0"
default-features = false
optional = true

[dependencies.once_cell]
version = "1.8.0"
default-features = false
optional = true

[features]
default = ["std"]
std = [
	"codec/std",
	"scale-info/std",
	"frame-support/std",
]
testing = [
	"ethers-signers",
	"once_cell",
	"nomad-core/testing",
	"signature/testing",
]