[package]
name = "pallet-asset-tx-payment"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/availproject/polkadot-sdk/"
description = "pallet to manage transaction payments in assets"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# Substrate dependencies
sp-core = { version = "21.0.0", workspace = true, default-features = false }
sp-io = { version = "23.0.0", workspace = true, default-features = false }
sp-runtime = { version = "24.0.0", workspace = true, default-features = false }
sp-std = { version = "8.0.0", workspace = true, default-features = false }

frame-support = { workspace = true, default-features = false }
frame-system = { version = "4.0.0-dev", default-features = false, path = "../../system" }
pallet-transaction-payment = { version = "4.0.0-dev", default-features = false, path = ".." }
frame-benchmarking = { version = "4.0.0-dev", workspace = true, default-features = false, optional = true }

# Other dependencies
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.195", optional = true }

[dev-dependencies]
serde_json = "1.0.85"

sp-storage = { version = "13.0.0", workspace = true, default-features = false }

pallet-assets = { version = "4.0.0-dev", workspace = true, default-features = false }
pallet-authorship = { version = "4.0.0-dev", workspace = true, default-features = false }
pallet-balances = { version = "4.0.0-dev", workspace = true, default-features = false, features = ["std"] }

[features]
default = ["std"]
std = [
	"scale-info/std",
	"serde",
	"codec/std",
	"sp-std/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"sp-io/std",
	"sp-core/std",
	"pallet-transaction-payment/std",
	"frame-benchmarking?/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
]
try-runtime = ["frame-support/try-runtime"]
