[package]
name = "da-primitives"
version = "0.2.2"
authors = []
edition = "2018"

[dependencies]
# Others
derive_more = "0.99.17"
log = { version = "0.4.8", default-features = false }
serde = { version = "1.0.121", optional = true, features = ["derive"] }
serde_json = { version = "1.0", optional = true }
thiserror-no-std = "2.0.2"

# Substrate
beefy-merkle-tree = { git = "https://github.com/paritytech/substrate.git/", branch = "polkadot-v0.9.13", default-features = false }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
frame-support = { version = "4.0.0-dev", default-features = false }
parity-util-mem = { version = "0.10.2", default-features = false, features = ["primitive-types"] }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }
sp-core = { version = "4.0.0-dev", default-features = false }
sp-io = { version = "4.0.0-dev", default-features = false }
sp-runtime = { version = "4.0.0-dev", default-features = false }
sp-runtime-interface = { version = "4.0.0-dev", default-features = false }
sp-std = { version = "4.0.0-dev", default-features = false }

[dev-dependencies]
hex-literal = "0.3.4"
test-case = "1.2.3"

[features]
default = ["std"]
std = [
	"serde",
	"serde_json",
	"codec/std",
	"scale-info/std",
	"log/std",
	"sp-core/std",
	"sp-std/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-runtime-interface/std",
	"frame-support/std",
	"parity-util-mem/std",
	"beefy-merkle-tree/std",
]

header-backward-compatibility-test = []
