[package]
name = "frame-executive"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME executives engine"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = [
	"derive",
] }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"] }
frame-support = { version = "4.0.0-dev", default-features = false }
frame-system = { version = "4.0.0-dev", default-features = false }
frame-try-runtime = { version = "0.10.0-dev", default-features = false, optional = true }
sp-core = { version = "21.0.0", default-features = false }
sp-io = { version = "23.0.0", default-features = false }
sp-runtime = { version = "24.0.0", default-features = false }
sp-std = { version = "8.0.0", default-features = false }
sp-tracing = { version = "10.0.0", default-features = false }

[dev-dependencies]
array-bytes = "6.1"
pallet-balances = { version = "4.0.0-dev" }
pallet-transaction-payment = { version = "4.0.0-dev" }
sp-core = { version = "21.0.0" }
sp-inherents = { version = "4.0.0-dev" }
sp-io = { version = "23.0.0" }
sp-version = { version = "22.0.0" }

[features]
default = ["std"]
with-tracing = ["sp-tracing/with-tracing"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"frame-try-runtime/std",
	"scale-info/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-tracing/std",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-try-runtime/try-runtime",
	"sp-runtime/try-runtime",
	"frame-system/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-transaction-payment/try-runtime"
]
