[package]
name = "frame-executive"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME executives engine"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
da-primitives = { version = "0.4", default-features = false }

codec = { package = "parity-scale-codec", version = "3", default-features = false, features = [
	"derive",
] }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
frame-support = { version = "4.0.0-dev", default-features = false }
frame-system = { version = "4.0.0-dev", default-features = false }
frame-try-runtime = { version = "0.10.0-dev", default-features = false, optional = true }
sp-runtime = { version = "7.0.0", default-features = false }
sp-tracing = { version = "5.0.0", default-features = false}
sp-std = { version = "5.0.0", default-features = false }
sp-io = { version = "7.0.0", default-features = false }
sp-core = { version = "7.0.0", default-features = false }


[dev-dependencies]
array-bytes = "4.1"
hex-literal = "0.3.4"
pallet-balances = "4.0.0-dev"
pallet-transaction-payment = "4.0.0-dev"
sp-version = "5"
sp-inherents = "4.0.0-dev"
pallet-babe = "4.0.0-dev"
mocked-runtime = { path = "../mocked_runtime" }
da-control = { path = "../dactr" }

[features]
default = ["std"]
with-tracing = ["sp-tracing/with-tracing"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-tracing/std",
	"da-primitives/std",
]
try-runtime = [
	"frame-support/try-runtime", 
	"frame-try-runtime/try-runtime" ,
	"da-primitives/try-runtime"
]
