[package]
name = "da-bridge"
version = "1.0.1"
authors = [""]
edition = "2021"
license = "Apache-2.0"
homepage = ""
repository = ""
description = "Data Attestation Bridge Module"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# Our crates
da-primitives = { version = "0.4", default-features = false }
nomad-core = { version = "0.1", default-features = false }
nomad-home = { path = "../home", default-features = false }

# 3rd-party 
serde = { version = "1.0.126", optional = true, features = ["derive"] }
codec = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
sp-core = { version = "7.0.0", default-features = false }
sp-std = { version = "5.0.0", default-features = false }
sp-io = { version = "7.0.0", default-features = false }
sp-runtime = { version = "7.0.0", default-features = false }
sp-arithmetic = { version = "5", default-features = false }
frame-support = { version = "4.0.0-dev", default-features = false }
frame-system = { version = "4.0.0-dev", default-features = false }
primitive-types = { version = "0.12", default-features = false }
frame-benchmarking = { version = "4.0.0-dev", default-features = false, optional = true }
hex-literal = "0.3.4"


[dev-dependencies]
rand = "0.8.5"
hex-literal = "0.3.4"
frame-executive = "4.0.0-dev"
pallet-transaction-payment = "4.0.0-dev"
da-control = { path = "../../dactr" }
nomad-base = "0.1" 
nomad-merkle  = "0.1" 
nomad-updater-manager = { path = "../updater-manager" }

[features]
default = ["std"]
std = [
	"codec/std",
	"scale-info/std",
	"frame-support/std",
	"frame-system/std",
	"frame-benchmarking/std",
	"nomad-home/std",
	"nomad-core/std",
	"da-primitives/std",
]

runtime-benchmarks = [
	"frame-benchmarking",
	"sp-runtime/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
]
try-runtime = ["frame-support/try-runtime"]
