[package]
name = "signature"
version = "0.1.0"
edition = "2021"
authors = ["Luke Tchang <luke@nomad.xyz>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/ltchang2019/no-std-eth-signature"
description = """
`ethers-rs` signature implemented as no_std.
"""

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Substrate
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }
sp-std = { version = "4.0.0-dev", default-features = false }
sp-core = { version = "4.0.0-dev", default-features = false }
sp-io = { version = "4.0.0-dev", default-features = false }
frame-support = { version = "4.0.0-dev", default-features = false }
parity-util-mem = { version = "0.10.2", default-features = false, features = ["primitive-types"] }
primitive-types = { version = "0.10.1", default-features = false, features = ["scale-info", "codec"] }
rlp = { version = "0.5.0", default-features = false }
ethabi = { version = "17.0.0", default-features = false, features = ["rlp"] }
arrayvec = { version = "0.7.2", default-features = false }
rlp-derive = { version = "0.1.0", default-features = false }

# crypto
elliptic-curve = { version = "0.11.12", default-features = false }
generic-array = { version = "0.14.5", default-features = false }
k256 = { version = "0.10.4", default-features = false, features = ["keccak256", "ecdsa"] }
tiny-keccak = { version = "2.0.2", default-features = false }

# misc
thiserror-no-std = "2.0.1"
hex = { version = "0.4.3", default-features = false }
once_cell = { version = "1.12.0", optional = true }

[dependencies.ethers-core]
version = "0.13.0"
default-features = false
optional = true

[dependencies.byte-slice-cast]
version  = "1.2.1"
default-features = false
optional = true

[features]
default = ["std"]
std = [
	"codec/std",
	"scale-info/std",
	"frame-support/std",
]
testing = ["ethers-core", "byte-slice-cast"]