[package]
name = "signature"
version = "0.1.1"
authors = ["Luke Tchang <luke@nomad.xyz>"]
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/ltchang2019/no-std-eth-signature"
description = """
`ethers-rs` signature implemented as no_std.
"""

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = { version = "0.7.2", default-features = false }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
elliptic-curve = { version = "0.11.12", default-features = false }
ethabi = { version = "17.0.0", default-features = false, features = ["rlp"] }
ethers-core = { version = "0.13.0", optional = true }
frame-support = { version = "4.0.0-dev", default-features = false }
generic-array = { version = "0.14.5", default-features = false }
hex = { version = "0.4.3", default-features = false }
k256 = { version = "0.10.4", default-features = false, features = ["keccak256", "ecdsa"] }
once_cell = { version = "1.12.0", optional = true }
parity-util-mem = { version = "0.10.2", default-features = false, features = ["primitive-types"] }
primitive-types = { version = "0.10.1", default-features = false, features = ["scale-info", "codec"] }
rlp = { version = "0.5.0", default-features = false }
rlp-derive = { version = "0.1.0", default-features = false }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }
serde = { version = "1.0", default-features = false, optional = true, features = ["derive"] }
sp-core = { version = "4.0.0-dev", default-features = false }
sp-io = { version = "4.0.0-dev", default-features = false }
sp-std = { version = "4.0.0-dev", default-features = false }
thiserror-no-std = "2.0.2"
tiny-keccak = { version = "2.0.2", default-features = false }

[dev-dependencies]
byte-slice-cast = "1.2.1"

[features]
default = ["std"]
std = [
	"serde",
	"primitive-types/serde",
	"codec/std",
	"scale-info/std",
	"frame-support/std",
	"ethers-core",
]
