[package]
name = "kate-recovery"
version = "0.1.0"
authors = ["Denis Ermolin <denis.ermolin@matic.network>"]
edition = "2018"

[dependencies]
thiserror = "1.0"
dusk-plonk = { git = "https://github.com/maticnetwork/plonk.git", branch = "v0.8.2-polygon-4" }
dusk-bytes = { version = "0.1.5" }
getrandom = { version = "0.2", features = ["js"] }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
rand = "0.8.4" 
rand_chacha = "0.3"
