[package]
name = "kate-recovery"
version = "0.1.2"
authors = ["Denis Ermolin <denis.ermolin@matic.network>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
dusk-bytes = "0.1.6"
dusk-plonk = { git = "https://github.com/maticnetwork/plonk.git", tag = "v0.12.0-polygon-1" }
getrandom = { version = "0.2", features = ["js"] }
serde = { version = "1.0", features = ["derive"] }
thiserror-no-std = "2.0.2"

[dev-dependencies]
rand = "0.8.4"
rand_chacha = "0.3"

[features]
default = ["std"]
std = []
